spring.application.name=motivational_chat_app

server.port = 8080

spring.datasource.url=jdbc:mysql://localhost:3306/motivation
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.error.include-message=always
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
