INSERT INTO quote (author, text) VALUES ('Maya Angelou', 'Vous ne pouvez pas épuiser votre créativité. Plus vous l’utilisez, plus vous en avez.');
INSERT INTO quote (author, text) VALUES ('Elon Musk', 'Lorsque quelque chose est suffisamment important, vous le faites même si les chances ne sont pas en votre faveur.');
INSERT INTO quote (author, text) VALUES ('Isaac Newton', 'Les hommes construisent trop de murs et pas assez de ponts.');
INSERT INTO quote (author, text) VALUES ('Marie Curie', 'Dans la vie, rien n’est à craindre, tout est à comprendre.');
INSERT INTO quote (author, text) VALUES ('Winston Churchill', 'Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme.');
INSERT INTO quote (author, text) VALUES ('Franklin D. Roosevelt', 'Le seul moyen de faire du bon travail est d’aimer ce que vous faites.');
INSERT INTO quote (author, text) VALUES ('Bill Gates', 'Il est bon de célébrer le succès, mais il est plus important de tirer les leçons de l’échec.');
INSERT INTO quote (author, text) VALUES ('Coco Chanel', 'Le succès est souvent atteint par ceux qui ne savent pas que l’échec est inévitable.');
INSERT INTO quote (author, text) VALUES ('Albert Einstein', 'L’imagination est plus importante que le savoir.');
INSERT INTO quote (author, text) VALUES ('Steve Jobs', 'L’innovation, c’est ce qui distingue un leader d’un suiveur.');
INSERT INTO quote (author, text) VALUES ('Nelson Mandela', 'L’éducation est l’arme la plus puissante pour changer le monde.');
INSERT INTO quote (author, text) VALUES ('Oprah Winfrey', 'Faites ce que vous avez à faire jusqu’à ce que vous puissiez faire ce que vous voulez faire.');
INSERT INTO quote (author, text) VALUES ('Confucius', 'Choisissez un travail que vous aimez et vous n’aurez pas à travailler un seul jour de votre vie.');
INSERT INTO quote (author, text) VALUES ('Theodore Roosevelt', 'Croyez en vous et vous aurez déjà parcouru la moitié du chemin.');
INSERT INTO quote (author, text) VALUES ('Mark Twain', 'Donnez à chaque jour la chance de devenir le plus beau jour de votre vie.');
INSERT INTO quote (author, text) VALUES ('Henry Ford', 'L’échec est seulement l’opportunité de recommencer d’une façon plus intelligente.');
INSERT INTO quote (author, text) VALUES ('Thomas Edison', 'Notre plus grande faiblesse réside dans l’abandon. La façon la plus sûre de réussir est d’essayer encore une fois.');
INSERT INTO quote (author, text) VALUES ('Eleanor Roosevelt', 'Personne ne peut vous faire sentir inférieur sans votre consentement.');
INSERT INTO quote (author, text) VALUES ('Bruce Lee', 'Soyez heureux, mais jamais satisfait.');