INSERT INTO quote (author, text) VALUES ('Albert Einstein', 'La créativité, c’est l’intelligence qui s’amuse.');
INSERT INTO quote (author, text) VALUES ('Steve Jobs', 'Stay hungry, stay foolish.');
INSERT INTO quote (author, text) VALUES ('Nelson Mandela', 'Cela semble toujours impossible, jusqu’à ce qu’on le fasse.');
INSERT INTO quote (author, text) VALUES ('Albert Einstein', 'La logique vous mènera d’un point A à un point B. L’imagination vous mènera partout.');
INSERT INTO quote (author, text) VALUES ('Steve Jobs', 'Votre temps est limité, ne le gâchez pas en menant une existence qui n’est pas la vôtre.');
INSERT INTO quote (author, text) VALUES ('Walt Disney', 'La meilleure façon de commencer est d’arrêter de parler et de commencer à faire.');
INSERT INTO quote (author, text) VALUES ('Confucius', 'Une petite impatience ruine un grand projet.');
INSERT INTO quote (author, text) VALUES ('Theodore Roosevelt', 'Faites ce que vous pouvez, avec ce que vous avez, là où vous êtes.');
INSERT INTO quote (author, text) VALUES ('Oprah Winfrey', 'Entourez-vous uniquement de gens qui vont vous tirer vers le haut.');
INSERT INTO quote (author, text) VALUES ('Mark Twain', 'Ils ne savaient pas que c’était impossible, alors ils l’ont fait.');
INSERT INTO quote (author, text) VALUES ('Henry Ford', 'Que vous pensiez être capable ou ne pas être capable, dans les deux cas vous avez raison.');
INSERT INTO quote (author, text) VALUES ('Léonard de Vinci', 'Les détails font la perfection, et la perfection n’est pas un détail.');
INSERT INTO quote (author, text) VALUES ('Thomas Edison', 'Je n’ai pas échoué. J’ai simplement trouvé 10 000 solutions qui ne fonctionnent pas.');
INSERT INTO quote (author, text) VALUES ('Eleanor Roosevelt', 'Le futur appartient à ceux qui croient en la beauté de leurs rêves.');
INSERT INTO quote (author, text) VALUES ('Bruce Lee', 'Ne crains pas l’échec. Dans les grands exploits, c’est lui qui enseigne.');
